package DieGameApp;

/**
* DieGameApp/PlayerIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DieGameApp.idl
* Friday, July 3, 2020 6:27:30 AM EEST
*/


//Player
public final class PlayerIntHolder implements org.omg.CORBA.portable.Streamable
{
  public DieGameApp.PlayerInt value = null;

  public PlayerIntHolder ()
  {
  }

  public PlayerIntHolder (DieGameApp.PlayerInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DieGameApp.PlayerIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DieGameApp.PlayerIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DieGameApp.PlayerIntHelper.type ();
  }

}
