package DieGameApp;


/**
* DieGameApp/ServerInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DieGameApp.idl
* Friday, July 3, 2020 6:27:30 AM EEST
*/


//Server
public interface ServerInt extends ServerIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInt
