package DieGameApp;


/**
* DieGameApp/PlayerIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DieGameApp.idl
* Friday, July 3, 2020 6:27:30 AM EEST
*/


//Player
public interface PlayerIntOperations 
{
  void callback (String msg);
} // interface PlayerIntOperations
