package DieGameApp;


/**
* DieGameApp/PlayerIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DieGameApp.idl
* Friday, July 3, 2020 6:27:30 AM EEST
*/


//Player
abstract public class PlayerIntHelper
{
  private static String  _id = "IDL:DieGameApp/PlayerInt:1.0";

  public static void insert (org.omg.CORBA.Any a, DieGameApp.PlayerInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DieGameApp.PlayerInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DieGameApp.PlayerIntHelper.id (), "PlayerInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DieGameApp.PlayerInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PlayerIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DieGameApp.PlayerInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DieGameApp.PlayerInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DieGameApp.PlayerInt)
      return (DieGameApp.PlayerInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DieGameApp._PlayerIntStub stub = new DieGameApp._PlayerIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DieGameApp.PlayerInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DieGameApp.PlayerInt)
      return (DieGameApp.PlayerInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DieGameApp._PlayerIntStub stub = new DieGameApp._PlayerIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
