package DieGameApp;


/**
* DieGameApp/ServerIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DieGameApp.idl
* Friday, July 3, 2020 6:27:30 AM EEST
*/


//Server
public interface ServerIntOperations 
{
  int MRandom (String player_name);
  void RegisterCallback (DieGameApp.PlayerInt player);
} // interface ServerIntOperations
